import type { Deal } from '@/entities/deal/types';

const mockDeals: Deal[] = [
  {
    id: 'd1',
    title: 'Implantação CRM',
    contactName: 'Joana Ribeiro',
    company: 'Acme S.A.',
    amount: 48000,
    currency: 'BRL',
    stage: 'proposal',
    updatedAt: '2026-04-10T14:32:00.000Z',
  },
  {
    id: 'd2',
    title: 'Licenças anuais',
    contactName: 'Carlos Mendes',
    company: 'Nortech Ltda.',
    amount: 126500,
    currency: 'BRL',
    stage: 'negotiation',
    updatedAt: '2026-04-11T09:15:00.000Z',
  },
  {
    id: 'd3',
    title: 'Integração ERP',
    contactName: 'Marina Alves',
    company: 'Vigor Indústria',
    amount: 32000,
    currency: 'BRL',
    stage: 'qualification',
    updatedAt: '2026-04-08T17:02:00.000Z',
  },
  {
    id: 'd4',
    title: 'Consultoria inicial',
    contactName: 'Rafael Souza',
    company: 'Luma Saúde',
    amount: 12800,
    currency: 'BRL',
    stage: 'lead',
    updatedAt: '2026-04-07T11:48:00.000Z',
  },
  {
    id: 'd5',
    title: 'Renovação de contrato',
    contactName: 'Patrícia Lima',
    company: 'Orbitek',
    amount: 89000,
    currency: 'BRL',
    stage: 'closing',
    updatedAt: '2026-04-05T08:20:00.000Z',
  },
  {
    id: 'd6',
    title: 'Piloto de IA',
    contactName: 'Eduardo Braga',
    company: 'Solari Tech',
    amount: 22000,
    currency: 'BRL',
    stage: 'initial_contact',
    updatedAt: '2026-04-09T13:10:00.000Z',
  },
  {
    id: 'd7',
    title: 'Expansão de licenças',
    contactName: 'Fernanda Costa',
    company: 'Acme S.A.',
    amount: 15400,
    currency: 'BRL',
    stage: 'lead',
    updatedAt: '2026-04-06T10:05:00.000Z',
  },
  {
    id: 'd8',
    title: 'Automação comercial',
    contactName: 'Bruno Teixeira',
    company: 'Delta Varejo',
    amount: 67500,
    currency: 'BRL',
    stage: 'negotiation',
    updatedAt: '2026-04-11T16:40:00.000Z',
  },
];

export async function fetchDeals(): Promise<Deal[]> {
  return Promise.resolve(mockDeals);
}
